version: '3'
services:
  telegram_bot:
    build: .
    command: sh -c "python bot/__init__.py"
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      BOT_TOKEN: <paste_your_bot_token_here>
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: hh_update_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: hh_update_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /srv/docker/postgres:/var/lib/postgresql
