version: '3'
services:
  telegram:
    build: .
    command: sh -c "python main.py"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      BOT_TOKEN: <paste yout bot token here>
      REDIS_URI: redis
      REDIS_PORT: 6379
  redis:
    image: redis:4-alpine
